services:
  server:
      build: .
      depends_on:
       postgres:
         condition: service_healthy
      environment:
        PROD_DB_URL: "host=postgres user=root password=root dbname=url-short port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      ports:
        - 8000:8000
      develop:
        watch:
          - path: .
            action: rebuild
  

  postgres:
    image: postgres:13-alpine
    container_name: url-shortner-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url-short
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U root -d url-short"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
  postgres-data: